romaingericot/travelive

- app/models/booking.rb
- app/models/review.rb
- app/models/tour.rb
- db/migrate/20200622145332_create_tours.rb
- db/migrate/20200622145957_create_bookings.rb
- db/migrate/20200622150053_create_reviews.rb
- db/migrate/20200622150441_add_role_to_user.rb
- db/migrate/20200622150503_add_description_to_user.rb
- db/migrate/20200622150618_add_first_name_to_user.rb
- db/migrate/20200622150632_add_last_name_to_user.rb
- db/schema.rb
- test/models/booking_test.rb
- test/models/review_test.rb
- test/models/tour_test.rb
> Add models

- app/controllers/bookings_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/tours_controller.rb
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/reviews/new.html.erb
- app/views/tours/index.html.erb
- app/views/tours/show.html.erb
- config/routes.rb
- test/controllers/bookings_controller_test.rb
- test/controllers/reviews_controller_test.rb
- test/controllers/tours_controller_test.rb
> Controller

- config/environments/production.rb
> Forcing SSL in Rails

- .gitignore
- app/models/booking.rb
- app/models/review.rb
- app/models/tour.rb
- app/models/user.rb
a checker @fguilloucamargo @EdouardCouten @romaingericot
> Validations

- db/seeds.rb
> add .png to url

- app/models/tour.rb
- app/views/tours/show.html.erb
- config/environments/development.rb
- db/seeds.rb
> correction seed with cloudinary

- app/models/tour.rb
- app/views/tours/show.html.erb
- db/seeds.rb
Tour model accepts many images now
> Tour with many images

- app/views/devise/registrations/new.html.erb
> complete form to sign up

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/bookings_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/tour.rb
- app/views/bookings/index.html.erb
- config/initializers/geocoder.rb
- package.json
- yarn.lock
Add a map in booking index and markers with the GPS city
> add a place and a marker with the tour city

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_tab.scss
- app/controllers/reviews_controller.rb
> review controller

- app/controllers/bookings_controller.rb
- db/migrate/20200624114028_add_coordinates_to_tours.rb
- db/schema.rb
- db/seeds.rb
In order to solve seed problem with geocode, I have added a latitude and longitude at Tours
I have added a booking to seed
> Add lat long to tours to solve seed problem

- app/assets/stylesheets/components/_navbar.scss
- app/controllers/bookings_controller.rb
- app/controllers/tours_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/bookings/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/tours/index.html.erb
> Index with map

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_tab.scss
- app/models/user.rb
- app/views/tours/show.html.erb
- config/initializers/geocoder.rb
> Show front

- app/assets/stylesheets/components/_map.scss
- app/controllers/tours_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/tours/index.html.erb
New search bar in the home with country and city
Zoom when search
> Search index

- app/views/users/show.html.erb
> Link to go to tour

- app/models/tour.rb
Add skip before action i n tour for index and show
> add skip before action

- db/seeds.rb
@fguilloucamargo @romaingericot @DGDGboy
> description and photos / seed

- app/assets/stylesheets/components/_demo-css-grid.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/jarallax.scss
- app/javascript/packs/application.js
- app/views/tours/show.html.erb
- package.json
- yarn.lock
Setting JS Jarallax for background images
> JS Jarallax

- app/controllers/tours_controller.rb
- app/views/tours/edit.html.erb
- app/views/users/show.html.erb
A guide can delete and update a tour
Layout tours in the user dashboard - all card can be clicked now
> Tour delete

- app/models/checkpoint.rb
- app/models/tour.rb
- db/migrate/20200629152337_create_checkpoints.rb
- db/schema.rb
- test/models/checkpoint_test.rb
> create checkpoint model

- app/assets/stylesheets/components/_formconnection.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/devise/sessions/new.html.erb
> bugfix form

- app/assets/stylesheets/components/_map.scss
- app/views/tours/_info_window.html.erb
> card style

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_tab.scss
- app/assets/stylesheets/components/_tourShow.scss
- app/views/tours/show.html.erb
rubrique Guide sur la showTour
> guide description

- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tourShow.scss
- app/views/guide/tours/index.html.erb
- app/views/users/show.html.erb
messsage si tour booké
message si aucun tour de booké
> User dashboard

- app/controllers/guide/tours_controller.rb
- app/views/guide/tours/live.html.erb
- db/migrate/20200630162547_add_progress_to_checkpoints.rb
> Progress checkpoint

- app/assets/stylesheets/components/_footer.scss
- app/views/tours/show.html.erb
- app/views/users/show.html.erb
add message unique si 0-1 ou plus de 1 tour reservé
add tours les plus populaires
add ce qu'en pense nos visiteurs
> dashborad ok

- app/controllers/tours_controller.rb
Add to Tours Controller :
`skip_before_action :authenticate_user!, only: [:index, :show]`
> Connexion without login

- app/controllers/bookings_controller.rb
- app/views/tours/show.html.erb
if current_user.bookings.map {|b| b.tour_id}.include?(@tour.id)
> double resa

- app/javascript/components/countdown.js
- app/views/tours/live.html.erb
Fix superposition navbar sur vue live
Fake counter for demo
> Livemapfix

- app/assets/stylesheets/components/_card.scss
- app/views/tours/_info_window.html.erb
- app/views/tours/show.html.erb
- app/views/users/show.html.erb
- db/seeds.rb
- db/seeds_complet.rb
@romaingericot @fguilloucamargo @DGDGboy
> card+seeds+icon

- app/controllers/guide/tours_controller.rb
- app/views/guide/tours/index.html.erb
- app/views/guide/tours/new.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbarhome.html.erb
formulairesur show guide quand pas de Tour
> form guide

- app/controllers/tours_controller.rb
- app/javascript/plugins/init_map_live.js
- app/views/tours/live.html.erb
Correction of map size and zoom refresh in live map
> Correction zoom live map

- app/assets/stylesheets/components/_map.scss
- app/javascript/plugins/init_map_live.js
- app/views/guide/checkpoints/index.json.jbuilder
Change layout map live 
Correction of popup map live
> change map and correction pop live

- app/views/guide/tours/index.html.erb
Change the routes of start button in guide dashboard
> change route of start button in guide dashboard

- app/controllers/guide/tours_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/guide/tours/edit.html.erb
- app/views/guide/tours/index.html.erb
- app/views/guide/tours/new.html.erb
- app/views/tours/show.html.erb
Un guide ne peut pas booker son propre tour
bug images sur creation d'un tour toujours existant
> fix bug guide book own tour

- app/views/tours/show.html.erb
- app/views/users/show.html.erb
@fguilloucamargo @romaingericot @DGDGboy 
- Change picto to card Tours-User
> changepicto-user

- app/assets/stylesheets/components/_map.scss
- app/javascript/plugins/init_mapbox.js
- app/views/tours/index.html.erb
Changing zoom init_map.js for different devices
> Map responsive

- app/assets/stylesheets/components/_navbar.scss
> Navbar responsive

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_tab.scss
- app/assets/stylesheets/components/_testimonial.scss
- app/assets/stylesheets/components/_tourShow.scss
- app/views/tours/show.html.erb
Add media queries and optimizations for mobile devices
> Tour details responsivity

- .travis.yml
For continuous integration on the project
> Continuous integration with Travis CI
